- name: Catalogue server
  hosts: catalogue
  become: yes
  tasks:
  - name: Removing old node version
    ansible.builtin.dnf:
      name: nodejs
      state: absent
      
  - name: Enabling nodejs-18 version 
    ansible.builtin.shell: dnf module enable nodejs:18 -y

  - name: Installing nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: Adding roboshop user
    ansible.builtin.user:
      name: roboshop

  - name: Create a directory if does not exist
    ansible.builtin.file:
      name: /app
      state: directory

  - name: Download the catalogue application code
    ansible.builtin.get_url:
      name: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp

  - name: Unarchive/unzipping catalogue file that is already on the remote machine
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: Change the working directory and run npm install
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: copying catalogue.service
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: catalogue reloading
    ansible.builtin.systemd:
      daemon_reload: yes

  # let's start after the data is loaded

  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo

  - name: Install mongodb client
    ansible.builtin.package:
      name: mongodb-org-shell
      state: present

  - name: get the categories count
    ansible.builtin.command:  mongo --host mongodb.jella.fun --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
    register: product_count

  # - name: print the count
  #   ansible.builtin.debug:
  #     msg: "product count: {{product_count}}"

  - name: load catalogue data
    ansible.builtin.command: mongo --host mongodb.jella.fun </app/schema/catalogue.js
    when: product_count.stdout == "0" # keep double quotes

  - name: Enabling and restarting service
    ansible.builtin.service:
      name: catalogue
      state: reloaded
      enabled: yes