- name: Catalogue server
  hosts: catalogue
  become: yes
  tasks:
  - name: Removing old node version
    ansible.builtin.dnf:
      name: nodejs
      state: absent

  - name: Installing nodejs18 version
    ansible.builtin.yum:
      name: "nodejs=18"
      state: present


#       ---
# - name: Install a specific version of a package
#   hosts: your_hosts_group
#   become: true
#   tasks:
#     - name: Install a specific version of the package
#       ansible.builtin.apt:
#         name: "your_package_name=1.2.3-1"
#         state: present
