- name: Catalogue server
  hosts: catalogue
  become: yes
  tasks:
  - name: Removing old node version
    ansible.builtin.dnf:
      name: nodejs
      state: absent
      
  - name: Enabling nodejs-18 version 
    ansible.builtin.shell: dnf module enable nodejs:18 -y

  - name: Installing nodejs
    ansible.builtin.package:
      name: nodejs
      state: present