- name: mysql server
  hosts: mysql
  become: true
  tasks:
  - name: disabling old mysql
    ansible.builtin.command: dnf module disable mysql -y

  - name: copying mysql repo
    ansible.builtin.copy:
      src: mysql.repo
      dest: /etc/yum.repos.d/mysql.repo

  - name: installing mysql server
    ansible.builtin.dnf:
      name: install mysql-community-server
      state: present

  - name: enabling and starting mysql
    ansible.builtin.service:
      name: mysqld
      enabled: yes
      state: started

  - name: updating credentials
    ansible.built.shell: mysql_secure_installation --set-root-pass RoboShop@1




