- name: shipping component
  hosts: shipping
  become: true
  tasks:
  - name: install maven
    ansible.builtin.package:
      name: maven
      state: present

  - name: useradd roboshop
    ansible.builtin.user:
      name: roboshop

  - name: removing app directory
    ansible.builtin.file:
      name: /app
      state: absent

  - name: creating app directory
    ansible.builtin.file:
      name: /app
      state: directory

  - name: downloading the application code
    ansible.builtin.get_url:
      url: curl -L -o /tmp/shipping.zip https://roboshop-builds.s3.amazonaws.com/shipping.zip
      src: /tmp

  - name: unzipping
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes