- name: web component
  hosts: web
  become: true
  hosts:
  - name: installing nginx y
    ansible.builtin.dnf:
      name: nginx
      state: started
  
  - name: removing default nginx content
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: create default nginx content
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: presnt
      
  - name: downloading code
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/web.zip
      dest: /tmp

  - name: unzipping code
    ansible.builtin.unarchive:
      src: /tmp/web.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: creating nginx reverse proxy configurations
    ansible.builtin.copy:
      src: roboshop.conf
      dest: /etc/nginx/default.d/roboshop.conf

  - name: enable and start nginx
    ansible.builtin.service:
      name: nginx
      enabled: yes
      state: started